### ISSUE TITLE
Find a specific task and cancel it

### ISSUE THREAD

**Issue by retorquere** [BalassaMarton/sequential-task-queue#3]
Is it possible to find a task (by the TaskOptions passed for example) and cancel it, even if it is not the current/next task?

**Comment by BalassaMarton** [comment]
See https://github.com/BalassaMarton/sequential-task-queue#task-cancellation

**Comment by retorquere** [comment]
But how can I find the task if I haven't saved it when I pushed it?

**Comment by BalassaMarton** [comment]
You can simply extend the queue class like this:
```ts
class MyQueue extends SequentialTaskQueue {
    private taskLookup: any = {};
    push(task: Function, options?: TaskOptions, key?: any): CancellablePromiseLike<any> {
        var res = super.push(task, options);
        if (key)
            this.taskLookup[key] = res;
        return res;
    }
    cancelByKey(key: any) {
        var item = this.taskLookup[key];
        if (item) {
            delete this.taskLookup[key];
            item.cancel();
        }
    }
}
```
I didn't test this code, but I assume you get the general idea.

**Comment by retorquere** [comment]
Super, I'll test.

**Comment by retorquere** [comment]
So if I use both argument passing and cancellation, does that mean that the task function signature becomes `(args, token) => { .... }`?
