### ISSUE TITLE
Possible race condition

### ISSUE THREAD

**Issue by AlexIII** [BalassaMarton/sequential-task-queue#6]
Correct me if I wrong, but it seems like there's race condition in the `push()` method.
Say the queue is empty and I call `push()` asynchronously, it then calls `next()` in which something like that happens:
```javascript
if (!this.currentTask) {
	var task = //find the next task. Potentially not very fast operation
	this.currentTask = task;
	...
}
```
Now if two or more calls of `next()` happen somewhat simultaneously (more precicely if evaluation of `!this.currentTask` in one call happens while other still searching for the next task), two tasks will start running simultaneously and the handle of one of them will be "lost".

**Comment by BalassaMarton** [comment]
Remember that JavaScript is fundamentally single-threaded.
Recommended reading: 
https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules
https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop

**Comment by AlexIII** [comment]
I'm relatively new to js, so thanks for the answer. I wrote a simple test and unsurprisingly confirmed that there's no race.
